language: java
jdk:
- oraclejdk8
before_install:
 - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube -Dsonar.projectKey=sriram-koushik_project-euler -Dsonar.organization=sriram-koushik-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=975203e78f60fcd4e5141aab33dca234555ce8ef
after_success:
- bash <(curl -s https://codecov.io/bash)