language: java

before_install:
 - chmod +x gradlew

script: 
- ./gradlew sonarqube -Dsonar.projectKey=sriram-koushik_project-euler -Dsonar.organization=sriram-koushik-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=975203e78f60fcd4e5141aab33dca234555ce8ef

jdk:
- oraclejdk8

after_success:
- ./gradlew jacocoTestReport coveralls